import { integer, json, pgTable, timestamp, varchar } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

export const operationLogs = pgTable("sys_operation_log", {
  id: varchar({ length: 36 }).primaryKey().notNull(),
  userId: varchar({ length: 36 }).notNull(),
  username: varchar({ length: 50 }).notNull(),
  domain: varchar({ length: 100 }).notNull(),
  moduleName: varchar({ length: 100 }).notNull(),
  description: varchar({ length: 500 }).notNull(),
  requestId: varchar({ length: 36 }).notNull(),
  method: varchar({ length: 10 }).notNull(),
  url: varchar({ length: 500 }).notNull(),
  ip: varchar({ length: 45 }).notNull(),
  userAgent: varchar({ length: 500 }),
  params: json(),
  body: json(),
  response: json(),
  startTime: timestamp().notNull(),
  endTime: timestamp().notNull(),
  duration: integer().notNull(),
  createdAt: timestamp().defaultNow().notNull(),
});

export const selectOperationLogSchema = createSelectSchema(operationLogs, {
  id: schema => schema.describe("操作日志ID"),
  userId: schema => schema.describe("用户ID"),
  username: schema => schema.describe("用户名"),
  domain: schema => schema.describe("域名"),
  moduleName: schema => schema.describe("模块名称"),
  description: schema => schema.describe("操作描述"),
  requestId: schema => schema.describe("请求ID"),
  method: schema => schema.describe("HTTP方法"),
  url: schema => schema.describe("访问URL"),
  ip: schema => schema.describe("IP地址"),
  userAgent: schema => schema.describe("用户代理"),
  params: schema => schema.describe("请求参数"),
  body: schema => schema.describe("请求体"),
  response: schema => schema.describe("响应内容"),
  startTime: schema => schema.describe("开始时间"),
  endTime: schema => schema.describe("结束时间"),
  duration: schema => schema.describe("持续时间(毫秒)"),
  createdAt: schema => schema.describe("创建时间"),
});

export const insertOperationLogSchema = createInsertSchema(operationLogs, {
  userId: schema => schema.describe("用户ID"),
  username: schema => schema.describe("用户名"),
  domain: schema => schema.describe("域名"),
  moduleName: schema => schema.describe("模块名称"),
  description: schema => schema.describe("操作描述"),
  requestId: schema => schema.describe("请求ID"),
  method: schema => schema.describe("HTTP方法"),
  url: schema => schema.describe("访问URL"),
  ip: schema => schema.describe("IP地址"),
  userAgent: schema => schema.describe("用户代理"),
  params: schema => schema.describe("请求参数"),
  body: schema => schema.describe("请求体"),
  response: schema => schema.describe("响应内容"),
  startTime: schema => schema.describe("开始时间"),
  endTime: schema => schema.describe("结束时间"),
  duration: schema => schema.describe("持续时间(毫秒)"),
}).omit({
  id: true,
  createdAt: true,
});
