shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - reselect
  - semver
  - effect

packages:
  - plugins

onlyBuiltDependencies:
  - "@fission-ai/openspec"
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - simple-git-hooks
