minimumReleaseAge: 0
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - reselect
  - semver
  - effect

packages:
  - plugins

catalog:
  "@oxc-project/types": ^0.132.0
  oxc-parser: ^0.132.0
  vite: ^8.0.14

onlyBuiltDependencies:
  - "@fission-ai/openspec"
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - simple-git-hooks

allowBuilds:
  "@fission-ai/openspec": true
  esbuild: true
  msgpackr-extract: true
  simple-git-hooks: true
