/* eslint-disable unicorn/filename-case */
/* eslint-disable no-console */

import db from "@/db";
import { casbinRule, sysRole } from "@/db/schema";

export async function initCasbinRule() {
  // 获取角色数据
  const roles = await db.select({ id: sysRole.id, code: sysRole.code }).from(sysRole);

  const superRole = roles.find(r => r.code === "ROLE_SUPER");
  const adminRole = roles.find(r => r.code === "ROLE_ADMIN");
  const userRole = roles.find(r => r.code === "ROLE_USER");

  if (!superRole || !adminRole || !userRole) {
    throw new Error("未找到必要的角色数据");
  }

  const data = [
    // 超级管理员拥有所有权限
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "authorization",
      v2: "assign-permission",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "authorization",
      v2: "assign-routes",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "authorization",
      v2: "assign-users",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-user",
      v2: "create",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-user",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-user",
      v2: "update",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-user",
      v2: "delete",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-role",
      v2: "create",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-role",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-role",
      v2: "update",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-role",
      v2: "delete",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-menu",
      v2: "create",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-menu",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-menu",
      v2: "update",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-menu",
      v2: "delete",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-domain",
      v2: "create",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-domain",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-domain",
      v2: "update",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "sys-domain",
      v2: "delete",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "api-endpoint",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "login-log",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_SUPER",
      v1: "operation-log",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    // 普通管理员权限
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "sys-user",
      v2: "create",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "sys-user",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "sys-user",
      v2: "update",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "sys-role",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "sys-menu",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "login-log",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_ADMIN",
      v1: "operation-log",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    // 普通用户权限
    {
      ptype: "p",
      v0: "ROLE_USER",
      v1: "dashboard",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_USER",
      v1: "profile",
      v2: "read",
      v3: "built-in",
      v4: null,
      v5: null,
    },
    {
      ptype: "p",
      v0: "ROLE_USER",
      v1: "profile",
      v2: "update",
      v3: "built-in",
      v4: null,
      v5: null,
    },
  ];

  await db.insert(casbinRule).values(data).onConflictDoNothing();
  console.log("Casbin 权限规则初始化完成");
}
