-- Auto-generated by scripts/sync-comments.ts
-- DO NOT EDIT MANUALLY

BEGIN;

COMMENT ON TABLE "casbin_rule" IS NULL;
COMMENT ON COLUMN "casbin_rule"."ptype" IS 'Policy type: p (permission policy) / g (role inheritance) / 策略类型：p（权限策略）/g（角色继承）';
COMMENT ON COLUMN "casbin_rule"."v0" IS 'Subject: role or user (p=sub, g=parent role/user) / 主体：角色或用户（p策略=sub，g策略=上级角色/用户）';
COMMENT ON COLUMN "casbin_rule"."v1" IS 'Object: business resource (p=obj, g=child role/user) / 对象：业务资源（p策略=obj，g策略=下级角色/用户）';
COMMENT ON COLUMN "casbin_rule"."v2" IS 'Action: business action (only used by p policy, empty string for g) / 动作：业务动作（仅p策略使用，g策略为空字符串）';
COMMENT ON COLUMN "casbin_rule"."v3" IS 'Reserved field (not in use, defaults to empty string) / 保留字段（暂不使用，默认空字符串）';
COMMENT ON COLUMN "casbin_rule"."v4" IS 'Reserved field (not in use, defaults to empty string) / 保留字段（暂不使用，默认空字符串）';
COMMENT ON COLUMN "casbin_rule"."v5" IS 'Reserved field (not in use, defaults to empty string) / 保留字段（暂不使用，默认空字符串）';

COMMENT ON TABLE "client_users" IS NULL;
COMMENT ON COLUMN "client_users"."ali_openid" IS 'Alipay openid / 支付宝 openid';
COMMENT ON COLUMN "client_users"."apple_openid" IS 'Apple Sign-In openid / 苹果登录 openid';
COMMENT ON COLUMN "client_users"."avatar" IS 'Avatar URL / 头像地址';
COMMENT ON COLUMN "client_users"."comment" IS 'Remark / 备注';
COMMENT ON COLUMN "client_users"."created_at" IS 'Creation time / 创建时间';
COMMENT ON COLUMN "client_users"."created_by" IS 'Created by / 创建人';
COMMENT ON COLUMN "client_users"."dcloud_appids" IS 'Allowed client appid list for login / 允许登录的客户端 appid 列表';
COMMENT ON COLUMN "client_users"."department_ids" IS 'Department ID list / 部门ID列表';
COMMENT ON COLUMN "client_users"."email" IS 'Email address / 邮箱地址';
COMMENT ON COLUMN "client_users"."email_confirmed" IS 'Email verification status / 邮箱验证状态';
COMMENT ON COLUMN "client_users"."enterprise_ids" IS 'Enterprise ID list / 企业ID列表';
COMMENT ON COLUMN "client_users"."gender" IS 'Gender / 性别';
COMMENT ON COLUMN "client_users"."id" IS 'ID, generated by uuid v7 / id，uuid v7 生成';
COMMENT ON COLUMN "client_users"."identities" IS 'Third-party platform identity info / 第三方平台身份信息';
COMMENT ON COLUMN "client_users"."invite_time" IS 'Invitation time / 受邀时间';
COMMENT ON COLUMN "client_users"."inviter_uids" IS 'All upstream inviter UIDs / 用户全部上级邀请者';
COMMENT ON COLUMN "client_users"."last_login_date" IS 'Last login time / 最后登录时间';
COMMENT ON COLUMN "client_users"."last_login_ip" IS 'IP address at last login / 最后登录时 IP 地址';
COMMENT ON COLUMN "client_users"."mobile" IS 'Mobile number / 手机号码';
COMMENT ON COLUMN "client_users"."mobile_confirmed" IS 'Mobile verification status / 手机号验证状态';
COMMENT ON COLUMN "client_users"."my_invite_code" IS 'User''s own invite code / 用户自身邀请码';
COMMENT ON COLUMN "client_users"."nickname" IS 'User nickname / 用户昵称';
COMMENT ON COLUMN "client_users"."password" IS 'Password, stored encrypted / 密码，加密存储';
COMMENT ON COLUMN "client_users"."password_secret_version" IS 'Password secret version / 密码密钥版本';
COMMENT ON COLUMN "client_users"."qq_openid" IS 'QQ openid for each platform / QQ各平台 openid';
COMMENT ON COLUMN "client_users"."qq_unionid" IS 'QQ unionid / QQ unionid';
COMMENT ON COLUMN "client_users"."realname_auth" IS 'Real-name authentication info / 实名认证信息';
COMMENT ON COLUMN "client_users"."register_date" IS 'Registration time / 注册时间';
COMMENT ON COLUMN "client_users"."register_env" IS 'Registration environment info / 注册环境信息';
COMMENT ON COLUMN "client_users"."register_ip" IS 'IP address at registration / 注册时 IP 地址';
COMMENT ON COLUMN "client_users"."role_ids" IS 'Role ID list / 角色ID列表';
COMMENT ON COLUMN "client_users"."score" IS 'User score / 用户积分';
COMMENT ON COLUMN "client_users"."status" IS 'User status / 用户状态';
COMMENT ON COLUMN "client_users"."third_party" IS 'Third-party platform token info / 第三方平台token等信息';
COMMENT ON COLUMN "client_users"."tokens" IS 'User token list / 用户token列表';
COMMENT ON COLUMN "client_users"."updated_at" IS 'Update time (with auto-update) / 更新时间 包含自动更新';
COMMENT ON COLUMN "client_users"."updated_by" IS 'Updated by / 更新人';
COMMENT ON COLUMN "client_users"."username" IS 'Username / 用户名';
COMMENT ON COLUMN "client_users"."wx_openid" IS 'WeChat openid for each platform / 微信各平台 openid';
COMMENT ON COLUMN "client_users"."wx_unionid" IS 'WeChat unionid / 微信 unionid';

COMMENT ON TABLE "system_dicts" IS 'Business dictionary table Used for dynamic configuration of various dictionary data (e.g., user status, order types) Dictionary items are stored as JSONB arrays, no separate dictionary items table needed 业务字典表 用于动态配置各种字典数据（如用户状态、订单类型等） 字典项使用 JSONB 数组存储，无需额外的字典项表';
COMMENT ON COLUMN "system_dicts"."code" IS 'Dictionary code (unique identifier, e.g., "user_status") / 字典编码（唯一标识，如 "user_status"）';
COMMENT ON COLUMN "system_dicts"."created_at" IS 'Creation time / 创建时间';
COMMENT ON COLUMN "system_dicts"."created_by" IS 'Created by / 创建人';
COMMENT ON COLUMN "system_dicts"."description" IS 'Dictionary description / 字典描述';
COMMENT ON COLUMN "system_dicts"."id" IS 'ID, generated by uuid v7 / id，uuid v7 生成';
COMMENT ON COLUMN "system_dicts"."items" IS 'Dictionary items array (stored as JSONB) / 字典项数组（使用 JSONB 存储）';
COMMENT ON COLUMN "system_dicts"."name" IS 'Dictionary name (e.g., "user status") / 字典名称（如 "用户状态"）';
COMMENT ON COLUMN "system_dicts"."status" IS 'Enabled/disabled status / 启用/禁用状态';
COMMENT ON COLUMN "system_dicts"."updated_at" IS 'Update time (with auto-update) / 更新时间 包含自动更新';
COMMENT ON COLUMN "system_dicts"."updated_by" IS 'Updated by / 更新人';

COMMENT ON TABLE "system_params" IS 'System parameters table Used for dynamic configuration of various system parameters (e.g., SMS signature, payment config, system switches) 系统参数表 用于动态配置各种系统参数（如短信签名、支付配置、系统开关等）';
COMMENT ON COLUMN "system_params"."created_at" IS 'Creation time / 创建时间';
COMMENT ON COLUMN "system_params"."created_by" IS 'Created by / 创建人';
COMMENT ON COLUMN "system_params"."description" IS 'Parameter description / 参数描述';
COMMENT ON COLUMN "system_params"."id" IS 'ID, generated by uuid v7 / id，uuid v7 生成';
COMMENT ON COLUMN "system_params"."key" IS 'Parameter key (unique identifier, e.g., "sms_sign") / 参数键（唯一标识，如 "sms_sign"）';
COMMENT ON COLUMN "system_params"."name" IS 'Parameter name (e.g., "SMS signature") / 参数名称（如 "短信签名"）';
COMMENT ON COLUMN "system_params"."status" IS 'Enabled/disabled status / 启用/禁用状态';
COMMENT ON COLUMN "system_params"."updated_at" IS 'Update time (with auto-update) / 更新时间 包含自动更新';
COMMENT ON COLUMN "system_params"."updated_by" IS 'Updated by / 更新人';
COMMENT ON COLUMN "system_params"."value" IS 'Parameter value (stored as string) / 参数值（字符串存储）';
COMMENT ON COLUMN "system_params"."value_type" IS 'Parameter value type (for frontend parsing) / 参数值类型（供前端解析）';

COMMENT ON TABLE "system_roles" IS NULL;
COMMENT ON COLUMN "system_roles"."created_at" IS 'Creation time / 创建时间';
COMMENT ON COLUMN "system_roles"."created_by" IS 'Created by / 创建人';
COMMENT ON COLUMN "system_roles"."description" IS NULL;
COMMENT ON COLUMN "system_roles"."id" IS NULL;
COMMENT ON COLUMN "system_roles"."name" IS NULL;
COMMENT ON COLUMN "system_roles"."status" IS NULL;
COMMENT ON COLUMN "system_roles"."updated_at" IS 'Update time (with auto-update) / 更新时间 包含自动更新';
COMMENT ON COLUMN "system_roles"."updated_by" IS 'Updated by / 更新人';

COMMENT ON TABLE "system_user_roles" IS NULL;
COMMENT ON COLUMN "system_user_roles"."role_id" IS NULL;
COMMENT ON COLUMN "system_user_roles"."user_id" IS NULL;

COMMENT ON TABLE "system_users" IS NULL;
COMMENT ON COLUMN "system_users"."avatar" IS NULL;
COMMENT ON COLUMN "system_users"."built_in" IS NULL;
COMMENT ON COLUMN "system_users"."created_at" IS 'Creation time / 创建时间';
COMMENT ON COLUMN "system_users"."created_by" IS 'Created by / 创建人';
COMMENT ON COLUMN "system_users"."id" IS 'ID, generated by uuid v7 / id，uuid v7 生成';
COMMENT ON COLUMN "system_users"."nick_name" IS NULL;
COMMENT ON COLUMN "system_users"."password" IS NULL;
COMMENT ON COLUMN "system_users"."status" IS NULL;
COMMENT ON COLUMN "system_users"."updated_at" IS 'Update time (with auto-update) / 更新时间 包含自动更新';
COMMENT ON COLUMN "system_users"."updated_by" IS 'Updated by / 更新人';
COMMENT ON COLUMN "system_users"."username" IS NULL;

COMMIT;
