apiVersion: v1
kind: Namespace
metadata:
  name: hono-template
  labels:
    name: hono-template
    app: hono-template
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hono-template-quota
  namespace: hono-template
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hono-template-limits
  namespace: hono-template
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
