apiVersion: v1
kind: Secret
metadata:
  name: hono-secrets
  namespace: hono-template
type: Opaque
stringData:
  # 数据库配置
  DB_PASSWORD: postgres
  DB_USER: postgres
  DB_NAME: postgres

  # JWT 密钥 - 生产环境请更换为随机生成的安全密钥
  CLIENT_JWT_SECRET: your-client-jwt-secret-change-in-production
  ADMIN_JWT_SECRET: your-admin-jwt-secret-change-in-production

  # PgBouncer 统计用户密码
  PGBOUNCER_STATS_PASSWORD: stats123

  # Grafana 管理员密码
  GRAFANA_ADMIN_PASSWORD: admin123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hono-config
  namespace: hono-template
data:
  # 应用配置
  NODE_ENV: production
  LOG_LEVEL: info
  PORT: "9999"

  # 数据库配置
  DB_HOST: postgres-service
  DB_PORT: "5432"
  PGBOUNCER_HOST: pgbouncer-service
  PGBOUNCER_PORT: "6432"

  # Redis 配置
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

  # 运行时配置
  IGNORE_MIGRATION_ERRORS: "false"
  IGNORE_SYNC_ERRORS: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: hono-template
data:
  init.sql: |
    -- 创建 PgBouncer 统计用户
    CREATE USER stats WITH PASSWORD 'stats123';
    GRANT CONNECT ON DATABASE postgres TO stats;
    GRANT SELECT ON pg_stat_database TO stats;
