global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Hono 应用程序指标
  - job_name: hono-app
    static_configs:
      - targets: ["host.docker.internal:9999"]
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # PgBouncer 连接池指标
  - job_name: pgbouncer
    static_configs:
      - targets: ["pgbouncer-exporter:9127"]
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL 数据库指标 (可选)
  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
    scrape_timeout: 10s
    # 如果不使用 postgres-exporter，可以注释掉这个配置

  # Redis 指标 (可选)
  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    scrape_timeout: 10s
    # 如果不使用 redis-exporter，可以注释掉这个配置

  # Prometheus 自身指标
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s

  # Node Exporter (系统指标，可选)
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    # 如果不使用 node-exporter，可以注释掉这个配置

# 告警规则 (可选)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
        # - alertmanager:9093

# 存储配置通过命令行参数设置 (见 docker-compose.yml)
